""""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#3&m1hqn#*qad*rravbqc&1$+gu^i-00sn=+(5$--b^nk861ls'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # ✅ Must be False in production

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Add your production domain here


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cps',  # Content Security Policy app

    # Your apps
    'bookshelf',
]

# Custom user model setting
AUTH_USER_MODEL = 'bookshelf.CustomUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cps.middleware.CSPMiddleware',  # Content Security Policy Middleware
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------
# SECURITY BEST PRACTICES
# -------------------------------

# Prevent browser XSS attacks
SECURE_BROWSER_XSS_FILTER = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Ensure cookies are sent over HTTPS only
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Security settings
# DEBUG must be False in production to prevent sensitive info leaks.
# CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE enforce HTTPS only cookies.
# CSP prevents XSS by allowing only self-hosted scripts/styles.

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)

"""
--------------------------------------------
HTTPS & Security Settings (Production)
--------------------------------------------

1. SECURE_SSL_REDIRECT=True
   Redirects all HTTP requests to HTTPS.

2. HSTS Settings
   SECURE_HSTS_SECONDS=31536000
   SECURE_HSTS_INCLUDE_SUBDOMAINS=True
   SECURE_HSTS_PRELOAD=True
   Ensures browsers only access the site via HTTPS for 1 year.

3. Secure Cookies
   SESSION_COOKIE_SECURE=True
   CSRF_COOKIE_SECURE=True
   Ensures cookies are only sent over HTTPS.

4. Security Headers
   X_FRAME_OPTIONS='DENY'
   SECURE_CONTENT_TYPE_NOSNIFF=True
   SECURE_BROWSER_XSS_FILTER=True
   Protects against clickjacking, MIME sniffing, and XSS attacks.

5. Deployment
   Use SSL/TLS certificate on server (Nginx or Apache) and proxy to Django.
"""


# Enforce HTTPS for all requests
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# --------------------------------------------
# Proxy SSL Header (Important for HTTPS behind a proxy)
# --------------------------------------------
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
